[package]
name = "nes"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4.0"
sdl2 = "0.38.0"
rand = "=0.7.3"
strum_macros = "0.25"
clap = { version = "4.4", features = ["derive"] }
indoc = "2"
